### ISSUE TITLE
Gradle failure: `Could not get resource 'https://s3-eu-west-1.amazonaws.com/furhat-maven/releases/khttp/khttp/1.0.0/khttp-1.0.0.pom'.`

### ISSUE THREAD

**Issue by jsalbr** [FurhatRobotics/tutorials#9]
Didn't know where to report that problem best.

I get an error when I try to build a project because access to the file hosted on amazonaws is forbidden:

``` 
Starting Gradle Daemon...
Gradle Daemon started in 2 s 865 ms

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\...\build.gradle' line: 58

* What went wrong:
A problem occurred evaluating root project '...'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not resolve khttp:khttp:1.0.0.
     Required by:
         project : > com.furhatrobotics.furhatos:furhat-commons:2.4.0
      > Could not resolve khttp:khttp:1.0.0.
         > Could not get resource 'https://s3-eu-west-1.amazonaws.com/furhat-maven/releases/khttp/khttp/1.0.0/khttp-1.0.0.pom'.
            > Could not HEAD 'https://s3-eu-west-1.amazonaws.com/furhat-maven/releases/khttp/khttp/1.0.0/khttp-1.0.0.pom'. Received status code 403 from server: Forbidden

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.GradleScriptException: A problem occurred evaluating root project '...'.
	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:93)
	at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl$2.run(DefaultScriptPluginFactory.java:237)
	at org.gradle.configuration.ProjectScriptTarget.addConfiguration(ProjectScriptTarget.java:77)
....

* Get more help at https://help.gradle.org
```

Looking forward to a quick solution.

**Comment by MathieuRH** [comment]
Hello, 
You'll be able to solve that issue by going to the build.gradle file in your project, going to the section that is labelled "repositories" and then adding the repository jcenter(). 
Building skills with the latest SDKs should have that fix integrated :)

**Comment by jsalbr** [comment]
Thanks, that helped.
